### ISSUE TITLE
Width on code blocks

### ISSUE THREAD

**Issue by DrewML** [v8/v8.dev#136]
Thank y'all for the v8 site - it's fantastic!

## Example Page
https://v8.dev/docs/build

## Screenshot
![image](https://user-images.githubusercontent.com/5233399/51568926-8b0ba280-1e60-11e9-835d-4b5a68fca293.png)

## Problem
The code blocks stretch out a bit too far on the right. These declarations are responsible:

```css
width: calc(100% + 4em);
width: calc(100% + var(--offset)*2);
```

Dropping the declaration(s) fixes the width.

## After Screenshot
![image](https://user-images.githubusercontent.com/5233399/51569006-c4441280-1e60-11e9-84be-2f419c64b711.png)

**Comment by mathiasbynens** [comment]
Thanks for bringing this up!

Unfortunately, we can’t just drop those CSS declarations, since the goal is for code blocks to be full-width. [Example](https://v8.dev/blog/spread-elements#spread-elements):

![](https://user-images.githubusercontent.com/81942/51852348-2b3f4c80-22e3-11e9-863a-d77e28a68d96.png)

The problem with the code blocks you highlighted is that they occur within indented lists, causing the slightly strange look. Ideally these code blocks would be full width as well, regardless of the current indentation level.

**Comment by tomayac** [comment]
It seems like adding a new rule to deal with this case fixes this:

```css
li pre {
  width: calc(100% + var(--offset));
}
```

The idea being to just add one offset instead of the usual case where you add two. I have pulled out the second code block off the list to show both behaviors:

![Screen Shot 2019-06-13 at 10 08 51](https://user-images.githubusercontent.com/145676/59415296-799d4580-8dc3-11e9-915f-114abbc7281a.png)

**Comment by tomayac** [comment]
(Deleted my initial post as I misunderstood the requirement)

```css
ol {
  /* We need to override the UA stylesheet default of 40px */
  padding-inline-start: var(--offset);
}

li pre {
  /* Now we account for the three offsets in total that we need to be too wide */
  width: calc(100% + 3 * var(--offset));
  /* To finally move the entire thing relatively one offset to the left */
  left: calc(-1 * var(--offset));
  position: relative;
}
```

The second code block has been artificially moved out of the `<ol>` to show the desired effect.

![Screen Shot 2019-06-13 at 10 56 48](https://user-images.githubusercontent.com/145676/59418811-f9c6a980-8dc9-11e9-802a-50382698aaa3.png)
