### ISSUE TITLE
FOUC with the dark theme on first page load or refresh

### ISSUE THREAD

**Issue by tophf** [v8/v8.dev#335]
A dark theme that always flashes a white frame on first page load or refresh isn't really working and I would even recommend disabling it until this is fixed, provided you don't want to blind your users.

![image](https://user-images.githubusercontent.com/1310400/75369770-1c0b4380-58d5-11ea-9538-26b594f455d9.png)

![image](https://user-images.githubusercontent.com/1310400/75370068-9cca3f80-58d5-11ea-8c8f-89bedda5f1e2.png)

Hopefully, it'd be simple to move the script/style to an earlier time slot. Otherwise, a general solution is either to use `<link>` with `media="(prefers-color-scheme: dark)"` in `<head>` or check the theme name in an inline `<script>` in `<head>` and toggle the corresponding `<link>` or `<style>` element if for whatever reason you don't want to rely on a media query.

**Comment by tomayac** [comment]
We initially had this, but decided to keep the CSS in one file. We can reconsider this decision, however, also the situation should improve now that `color-scheme` has landed as a [meta tag](https://chromestatus.com/feature/5330651267989504) and as a [CSS property](https://www.chromestatus.com/feature/6070987093180416). I’m currently out of office, but will have a look upon my return.

**Comment by tophf** [comment]
>We initially had this, but decided to keep the CSS in one file

Some other Google's apps like gmail, chromium-review.googlesource.com also have a long white frame at page load when a dark theme is configured in their settings. Every time I encounter it I can't but think that their developers have never used a dark theme in the past 15 years. Anyone who did use it (`Stylish` extension exists since 2005) knows it's absolutely crucial that there's no FOUC or white flashes at load.

Kinda obvious but I'll mention it anyway: unless you want to ignore older browsers intentionally, those new bleeding edge meta tags and properties are a nice *addition* to a more reliable solution.

**Comment by tophf** [comment]
The site is still trying to blind people so I ended up copying its dark theme into [Stylus](https://github.com/openstyles/stylus). Posting it here for anyone who stumbles on this issue.

```css
:root {
  --html-color: var(--nearwhite);
  --html-background: var(--black);
  --main-color: var(--nearwhite);
  --main-background: var(--darkestgray);
  --footer-color: var(--nearwhite);
  --footer-background: var(--darkgray);
  --main-and-footer-link-color: var(--yellow);
  --avatar-img-filter: grayscale(50%);
  --icon-no-support-filter: brightness(0.5) grayscale(100%);
  --note-color: var(--darkestgray);
  --note-background: var(--yellow);
  --tag-color: var(--nearwhite);
  --tag-background: var(--darkgray);
  --table-border: var(--lightgray);
  --logo-hover-background: var(--darkgray);
  --alt-table-row-background: #111;
  -webkit-font-smoothing: antialiased
}

:root figure img[src*=".png"]:not(.no-darkening),
:root figure img[src*=".svg"]:not(.no-darkening) {
  -webkit-filter: invert(.862745) hue-rotate(180deg);
  filter: invert(.862745) hue-rotate(180deg)
}

:root.dark {
  --note-background: #021721;
  --note-color: #bbb;
  --html-color: #bbb;
}
```
The last block is my customization to reduce the unconventionally bright text color to the commonly used levels.
